---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ncdf4)
library(data.table)
library(zoo)
library(lubridate)
library(ggplot2)
library(RcppRoll)

# Charger les données de précipitation et de masque
precipitation_file <- "../ResPartOfParis_total_precipitation_1960-1970.nc"
mask_file <- "../countries_gridded_0.1deg_v0.1_FRo.nc"

precip_nc <- nc_open(precipitation_file)
mask_nc <- nc_open(mask_file)

tp <- ncvar_get(precip_nc, "tp")
longitude <- ncvar_get(precip_nc, "longitude")
latitude <- ncvar_get(precip_nc, "latitude")
time <- ncvar_get(precip_nc, "time")

time_units <- ncatt_get(precip_nc, "time", "units")$value
time_origin <- sub("hours since ", "", time_units)
time_origin <- as.POSIXct(time_origin, tz = "UTC")
time_dates <- time_origin + hours(time)

mask_data <- ncvar_get(mask_nc, "country")
longitude_mask <- ncvar_get(mask_nc, "lon")
latitude_mask <- ncvar_get(mask_nc, "lat")

nc_close(precip_nc)
nc_close(mask_nc)

# Création des data.tables pour la précipitation et le masque
precip_dt <- data.table(
  expand.grid(
    longitude = longitude,
    latitude = latitude,
    time = time_dates
  ),
  tp = as.vector(tp)
)

mask_dt <- data.table(
  expand.grid(
    longitude = longitude_mask,
    latitude = latitude_mask
  ),
  country = as.vector(mask_data)
)

# Fusionner les tables de précipitation et de masque
setkey(precip_dt, longitude, latitude)
setkey(mask_dt, longitude, latitude)

precip_masked_dt <- merge(precip_dt, mask_dt, by = c("longitude", "latitude"), all.x = TRUE)
precip_masked_dt[, tp := ifelse(country >= 0.8, tp, NA)]

# Afficher une partie des données pour vérifier
head(precip_masked_dt)


```


```{r}

calculate_consecutive_dry_days <- function(data) {
  days_below_thresholds <- ifelse(data < 0.001, 1, 0)
  days_above_thresholds <- ifelse(days_below_thresholds == 0, 1, 0)

  cumsum_below <- cumsum(days_below_thresholds)
  das <- cumsum_below - na.locf(na.locf(cumsum_below * (days_below_thresholds == 0), fromLast = TRUE), na.rm = FALSE)
  
  cumsum_above <- cumsum(days_above_thresholds)
  days <- cumsum_above - na.locf(na.locf(cumsum_above * (days_above_thresholds == 0), fromLast = TRUE), na.rm = FALSE)
  
  return(days)
}

# Resample la précipitation par jour et appliquer la fonction de calcul des jours secs consécutifs
precip_masked_dt[, time_day := as.Date(time)]
daily_precip <- precip_masked_dt[, .(tp_daily = sum(tp, na.rm = TRUE)), by = .(longitude, latitude, time_day)]

daily_precip[, consecutive_dry_days := calculate_consecutive_dry_days(tp_daily), by = .(longitude, latitude)]

max_consecutive_dry_days_dt <- daily_precip[, .(max_dry_days = max(consecutive_dry_days, na.rm = TRUE)), by = .(longitude, latitude, year = year(time_day))]

# Supprimer les valeurs NA
max_consecutive_dry_days_dt <- max_consecutive_dry_days_dt[!is.na(max_dry_days)]

# Vérification des données
head(max_consecutive_dry_days_dt)


```


```{r}

standardize_metric <- function(metric, reference_period, area = NULL) {
  reference <- metric[year >= year(as.Date(reference_period[1])) & year <= year(as.Date(reference_period[2]))]
  metric[, month_val := month(as.Date(paste0(year, "-01-01")))]
  
  mean_vals <- reference[, .(mean_val = mean(max_dry_days, na.rm = TRUE)), by = month_val]
  std_vals <- reference[, .(sd_val = sd(max_dry_days, na.rm = TRUE)), by = month_val]
  
  metric <- merge(metric, mean_vals, by = "month_val", all.x = TRUE)
  metric <- merge(metric, std_vals, by = "month_val", all.x = TRUE)
  
  metric[, standardized := (max_dry_days - mean_val) / sd_val]
  
  if (!is.null(area) && area) {
    return(metric[, .(standardized = mean(standardized, na.rm = TRUE)), by = year])
  } else {
    return(metric)
  }
}

# Resample les jours secs consécutifs par mois et standardiser les anomalies
monthly_dry_days_dt <- max_consecutive_dry_days_dt[, .(max_dry_days = max(max_dry_days, na.rm = TRUE)), by = .(longitude, latitude, year, month = month(as.Date(paste0(year, "-01-01"))))]
reference_period <- c("1960-01-01", "1964-12-31")
standardized_dry_days_dt <- standardize_metric(monthly_dry_days_dt, reference_period)

# Afficher une partie des données pour vérifier
head(standardized_dry_days_dt)


```











